name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: yarn
        env:
          NUXT_APP_BASE_URL: ${{ secrets.NUXT_APP_BASE_URL  }}
          PROVIDER_GITHUB_CLIENT_ID: ${{ secrets.PROVIDER_GITHUB_CLIENT_ID }}
          PROVIDER_GITHUB_CLIENT_SECRET: ${{ secrets.PROVIDER_GITHUB_CLIENT_SECRET }}
          PROVIDER_TWITCH_CLIENT_ID: ${{ secrets.PROVIDER_TWITCH_CLIENT_ID }}
          PROVIDER_TWITCH_CLIENT_SECRET: ${{ secrets.PROVIDER_TWITCH_CLIENT_SECRET }}
          API_ROUTE_SECRET: ${{ secrets.API_ROUTE_SECRET }}
          SITE_GH_ORIGIN: ${{ secrets.SITE_GH_ORIGIN }}
          DATABASE_URL: ${{ vars.DATABASE_URL }}
        
      - name: Yanr postinstall
        uses: borales/actions-yarn@v4
        with:
           cmd: yarn postinstall
      
      - name: Build production bundle
        run: yarn build 
      
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist